### ISSUE TITLE
Setting compression strategy in C API

### ISSUE THREAD

**Issue by pwuertz** [brion/mtpng#10]
Hi, I was experimenting with the compression strategy setting of the `mtpng` cli tool. For a specific type of images I'm seeing a huge benefit in using RLE or Huffman instead of the default setting.

I don't really see a way of setting this option using the C-API though. Unfortunately I don't know anything about Rust, but I'd assume that a new wrapper method similar to `capi.rs/mtpng_encoder_options_set_filter` is required to expose this setting to C?

**Comment by pwuertz** [comment]
Cargo science approach to exposing strategy option in 432c560.

**Comment by bvibber** [comment]
Looks good, thanks for the patch! I'll merge and bump an update to the crate.

(Note I'm thinking of redoing the C API using cbindgen instead of writing it all manually, so any comments on the existing ergonomics are welcome!)

**Comment by bvibber** [comment]
merged and published 0.3.2. :)

**Comment by pwuertz** [comment]
Existing ergonimics are working out really well, thanks! I just finished an experimental  [python binding](https://github.com/pwuertz/mtpng/tree/python/python), using an intermediate C++ layer with pybind11.

This is how it looks from the python side now:
```python
import numpy as np
from pymtpng import encode_png, Filter, Strategy

img = np.eye(64, dtype=np.uint8) * 255

with open("test.png", "wb") as fh:
    encode_png(img, fh, filter=Filter.Adaptive, strategy=Strategy.Rle)
```

**Comment by bvibber** [comment]
Awesome! Give a shout if you run into anything else missing, weird or confusing. :D
