### ISSUE TITLE
expose "write_chunk" functionality

### ISSUE THREAD

**Issue by JasperDeSutter** [brion/mtpng#12]
The current API does not allow writing arbitrary chunks. This is because the `Writer` is not exposed on the `Encoder` struct, and the `writer` module is not public.
This is currently limiting me from using mtpng, as I need to be able to write extra/custom chunks other than allowed currently.
Maybe a new `write_chunk` method could be added to the `Encoder` that simply forwards to the inner `Writer`?

**Comment by bvibber** [comment]
Yes, something like that should be perfect for custom chunks. I'll take a peek at the code soon and see if I can hack it in. :)

**Comment by bvibber** [comment]
0.3.4 (5318501c209d775553e05762c9b5c68767f8f9b9) should resolve this, let me know if it's working for you!

**Comment by JasperDeSutter** [comment]
Thanks for adding this feature so fast! It's working perfectly fine for my needs.
