### ISSUE TITLE
Please document cargo "features"

### ISSUE THREAD

**Issue by mcclure** [brion/mtpng#27]
When running `cargo add` with this crate, it shows the following features are available but off by default:

- capi
- clap
- cli
- libc
- png
- time

I do not find documentation of these in the README, nor in the [docs.rs page](https://docs.rs/mtpng/0.3.5/mtpng/).

From a comment in the cargo.toml combined with implications in the README, I assume that "cli" is for building the command line version, "clap", "png" and "time" are helper features used by the cli and not directly relevant to a user, and I assume "capi" and "libc" are related to the WIP C frontend.  However, it would be helpful to have this all be explicitly stated in some piece of documentation, if only so that a user can check and know "no, I don't need any of these" (it is somewhat concerning to install a png encoder library and discover that the "png" feature is disabled :) ). Thanks!

**Comment by bvibber** [comment]
Yep, some of those are cause I couldn't figure out how else to compose things with the package layout I wanted. ;) 

The official user-visible ones (which I'll add to the readme...) are:

* `capi` -> adds the C-FFI-compatible wrapper exports and builds a `.so`; implies `libc`
* `cli` -> builds the command line test/demo tool, implies `clap`, `png`, `time`

If you just need to use it in a Rust prog you don't need to set any features.
