### ISSUE TITLE
Crates.io page shows no readme info

### ISSUE THREAD

**Issue by bvibber** [brion/mtpng#6]
https://crates.io/crates/mtpng doesnt show the readme as i expect from other projects

Not sure what have to do to fix that

**Comment by bvibber** [comment]
Fixed it, had to specify 'readme' entry pointing to readme.md

**Comment by waldyrious** [comment]
@brion shouldn't that be the default behavior? Maybe this could be reported as a suggestion to the Crates project. I found [this issue](https://github.com/rust-lang/crates.io/issues/1742) that seems to be suggesting the same thing, but the response is not clear to me.

**Comment by bvibber** [comment]
@waldyrious I expected it to act like Github and autodetect my common-named file, but having to specify it is not a big deal as long as it's documented. https://doc.rust-lang.org/cargo/reference/manifest.html doesn't seem to mention it except in an example listing, where it's explained well enough but I didn't find it on my first pass through the docs.

**Comment by waldyrious** [comment]
> I expected it to act like Github and autodetect my common-named file

I think that's a reasonable expectation, and see no reason why it shouldn't be the case.

> I didn't find it on my first pass through the docs.

So, even if it is undesirable for some reason to have the automatic README detection, better documentation seems clearly needed.

I would make either suggestion myself but I didn't understand the closing reasoning in the issue I linked above. Does it make sense to you? What are they saying would be the proper channel to report/request that?

**Comment by bvibber** [comment]
My understanding of the note there is that the field should be auto-filled by Cargo before it gets sent to crates.io, so they recommend opening an issue directly on Cargo's tracker: https://github.com/rust-lang/cargo/issues
